# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: Orlajayne1

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: Orlajayne1
    salt: "jkbgfd894hjhb363636vdfbh"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  dev.safewords.co.uk:
    env:
      db_password: Orlajayne1
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "$m0q(PXlt?f_1QXBqg/zQn?@lHX;NPJ#K|HPFA=VCuCu/MHK8.q3w;zj4oqhKAgc"
      secure_auth_key: "7ZR%:y]E8zOGmWOn,J.Z23K.e)GIEY!1Qt+&j.+#EB+sv:7CIu}<:x!oO6Bp%{0t"
      logged_in_key: "PI|n*RIJikxru=@Cb&xsDEb<;*:]DT6NuvpoNo+_idNVI%Xso}E=@Xu9qA-;ICz;"
      nonce_key: "Q]_B)lZ)zGJ1<*>a[Z6=?:wrAxB&z-f|9hMcM,QTF9M(C8&CHq_ngsP8r]u&YQ-p"
      auth_salt: "%+ifD$4w;2RnRUnY{l4+|0!<uOg!1c:k1,3-<L.N^V!u5)fJ,Cii^u>e*&b_y:Jz"
      secure_auth_salt: "}R/QQv(7=$OWLV`19nk{^taa3A86#My^E>6Qd3NOk3k/gDasJ?6ad>s=nfv08Xp1"
      logged_in_salt: ".Q._=:nMoIW6?|X_HOKC@_HC|7%2i]vm@TL]@5N@kQv*I!mbgx[=QBERB1:Xr;MD"
      nonce_salt: "RFs]AAj,#ePQsZK}4UX2Weht$=CKwM<|NU=,<xJ%ZZp^{_9,[0;*_gQ05*53>nYX"
